2021-05-18 22:51:45,053 INFO    MainThread:656829 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 22:51:45,053 INFO    MainThread:656829 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 22:51:45,053 INFO    MainThread:656829 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Weather-Clf/wandb/run-20210518_225145-36lxjsoq/logs/debug.log
2021-05-18 22:51:45,053 INFO    MainThread:656829 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Weather-Clf/wandb/run-20210518_225145-36lxjsoq/logs/debug-internal.log
2021-05-18 22:51:45,053 INFO    MainThread:656829 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb7943d34a8>
2021-05-18 22:51:45,054 INFO    MainThread:656829 [wandb_init.py:init():369] calling init triggers
2021-05-18 22:51:45,054 INFO    MainThread:656829 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 22:51:45,054 INFO    MainThread:656829 [wandb_init.py:init():418] starting backend
2021-05-18 22:51:45,054 INFO    MainThread:656829 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-18 22:51:45,056 INFO    MainThread:656829 [backend.py:ensure_launched():132] starting backend process...
2021-05-18 22:51:45,091 INFO    MainThread:656829 [backend.py:ensure_launched():137] started backend process with pid: 785135
2021-05-18 22:51:45,092 INFO    MainThread:656829 [wandb_init.py:init():423] backend started and connected
2021-05-18 22:51:45,105 INFO    MainThread:656829 [wandb_init.py:init():465] updated telemetry
2021-05-18 22:51:45,105 INFO    MainThread:656829 [wandb_init.py:init():484] communicating current version
2021-05-18 22:51:45,941 INFO    MainThread:656829 [wandb_init.py:init():489] got version response 
2021-05-18 22:51:45,941 INFO    MainThread:656829 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-18 22:51:46,670 INFO    MainThread:656829 [wandb_init.py:init():522] starting run threads in backend
2021-05-18 22:51:51,675 INFO    MainThread:656829 [wandb_run.py:_console_start():1565] atexit reg
2021-05-18 22:51:51,676 INFO    MainThread:656829 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-18 22:51:51,676 INFO    MainThread:656829 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-18 22:51:51,676 INFO    MainThread:656829 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-18 22:51:51,676 INFO    MainThread:656829 [wandb_init.py:init():546] run started, returning control to user process
2021-05-18 22:51:51,684 INFO    MainThread:656829 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-18 22:51:51,684 INFO    MainThread:656829 [jupyter.py:save_ipynb():268] looking for notebook: 00-main.ipynb
2021-05-18 22:51:52,344 INFO    MainThread:656829 [wandb_init.py:_pause_backend():253] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7fb7938bf6d8>
2021-05-18 22:51:58,381 INFO    MainThread:656829 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-18 22:51:58,381 INFO    MainThread:656829 [wandb_run.py:_restore():1507] restore
2021-05-18 22:51:58,385 INFO    MainThread:656829 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 21129
  total_bytes: 21129
}

2021-05-18 22:51:58,879 INFO    MainThread:656829 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 21129
  total_bytes: 21129
}

2021-05-18 22:51:59,692 INFO    MainThread:656829 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 21129
  total_bytes: 37613
}

2021-05-18 22:52:00,306 INFO    MainThread:656829 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 21129
  total_bytes: 37892
}

2021-05-18 22:52:00,408 INFO    MainThread:656829 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 37892
  total_bytes: 37892
}

2021-05-18 22:52:00,511 INFO    MainThread:656829 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 37892
  total_bytes: 37892
}

2021-05-18 22:52:00,613 INFO    MainThread:656829 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 37892
  total_bytes: 37892
}

2021-05-18 22:52:00,714 INFO    MainThread:656829 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 37892
  total_bytes: 37892
}

2021-05-18 22:52:00,816 INFO    MainThread:656829 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 37892
  total_bytes: 37892
}

2021-05-18 22:52:00,918 INFO    MainThread:656829 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 37892
  total_bytes: 37892
}

2021-05-18 22:52:01,019 INFO    MainThread:656829 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 37892
  total_bytes: 37892
}

2021-05-18 22:52:01,121 INFO    MainThread:656829 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
  artifact_count: 1
}
pusher_stats {
  uploaded_bytes: 37892
  total_bytes: 37892
}

2021-05-18 22:52:02,423 INFO    MainThread:656829 [wandb_run.py:_show_files():1879] logging synced files
