2021-05-18 20:24:44,595 INFO    MainThread:628774 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 20:24:44,595 INFO    MainThread:628774 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 20:24:44,595 INFO    MainThread:628774 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Weather-Clf/wandb/run-20210518_202444-2cnvf4vl/logs/debug.log
2021-05-18 20:24:44,595 INFO    MainThread:628774 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Weather-Clf/wandb/run-20210518_202444-2cnvf4vl/logs/debug-internal.log
2021-05-18 20:24:44,595 INFO    MainThread:628774 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc5473042e8>
2021-05-18 20:24:44,596 INFO    MainThread:628774 [wandb_init.py:init():369] calling init triggers
2021-05-18 20:24:44,596 INFO    MainThread:628774 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 20:24:44,596 INFO    MainThread:628774 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 34mmwvxt
2021-05-18 20:24:44,597 INFO    MainThread:628774 [wandb_run.py:finish():1208] finishing run ranuga-d/Weather-Clf/34mmwvxt
2021-05-18 20:24:44,597 INFO    MainThread:628774 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-18 20:24:44,597 INFO    MainThread:628774 [wandb_run.py:_restore():1507] restore
2021-05-18 20:24:44,602 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 704
  total_bytes: 704
}

2021-05-18 20:24:45,143 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 704
  total_bytes: 704
}

2021-05-18 20:24:45,309 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 704
  total_bytes: 17524
}

2021-05-18 20:24:45,978 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11771
  total_bytes: 17524
}

2021-05-18 20:24:46,080 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17486
  total_bytes: 17524
}

2021-05-18 20:24:46,183 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17486
  total_bytes: 17524
}

2021-05-18 20:24:46,285 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17486
  total_bytes: 17524
}

2021-05-18 20:24:46,386 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17486
  total_bytes: 17524
}

2021-05-18 20:24:46,488 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17486
  total_bytes: 17524
}

2021-05-18 20:24:46,589 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17486
  total_bytes: 17524
}

2021-05-18 20:24:46,691 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17486
  total_bytes: 17524
}

2021-05-18 20:24:46,792 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17486
  total_bytes: 17524
}

2021-05-18 20:24:46,894 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17486
  total_bytes: 17524
}

2021-05-18 20:24:46,995 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17524
  total_bytes: 17524
}

2021-05-18 20:24:47,098 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17524
  total_bytes: 17524
}

2021-05-18 20:24:47,199 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17524
  total_bytes: 17524
}

2021-05-18 20:24:47,301 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17524
  total_bytes: 17524
}

2021-05-18 20:24:47,402 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17524
  total_bytes: 17524
}

2021-05-18 20:24:47,504 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17524
  total_bytes: 17524
}

2021-05-18 20:24:47,605 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17524
  total_bytes: 17524
}

2021-05-18 20:24:48,902 INFO    MainThread:628774 [wandb_run.py:_show_files():1879] logging synced files
2021-05-18 20:24:48,906 INFO    MainThread:628774 [wandb_init.py:init():418] starting backend
2021-05-18 20:24:48,906 INFO    MainThread:628774 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-18 20:24:48,909 INFO    MainThread:628774 [backend.py:ensure_launched():132] starting backend process...
2021-05-18 20:24:48,944 INFO    MainThread:628774 [backend.py:ensure_launched():137] started backend process with pid: 637575
2021-05-18 20:24:48,945 INFO    MainThread:628774 [wandb_init.py:init():423] backend started and connected
2021-05-18 20:24:48,956 INFO    MainThread:628774 [wandb_init.py:init():465] updated telemetry
2021-05-18 20:24:48,956 INFO    MainThread:628774 [wandb_init.py:init():484] communicating current version
2021-05-18 20:24:49,842 INFO    MainThread:628774 [wandb_init.py:init():489] got version response 
2021-05-18 20:24:49,842 INFO    MainThread:628774 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-18 20:24:50,391 INFO    MainThread:628774 [wandb_init.py:init():522] starting run threads in backend
2021-05-18 20:24:55,397 INFO    MainThread:628774 [wandb_run.py:_console_start():1565] atexit reg
2021-05-18 20:24:55,397 INFO    MainThread:628774 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-18 20:24:55,397 INFO    MainThread:628774 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-18 20:24:55,397 INFO    MainThread:628774 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-18 20:24:55,397 INFO    MainThread:628774 [wandb_init.py:init():546] run started, returning control to user process
2021-05-18 20:24:55,425 INFO    MainThread:628774 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-18 20:24:55,426 INFO    MainThread:628774 [jupyter.py:save_ipynb():268] looking for notebook: 00-main.ipynb
2021-05-18 20:24:55,936 INFO    MainThread:628774 [wandb_init.py:_pause_backend():253] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7fc548beeef0>
2021-05-18 20:25:22,117 INFO    MainThread:628774 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-18 20:25:22,120 INFO    MainThread:628774 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-18 20:25:22,121 INFO    MainThread:628774 [jupyter.py:save_ipynb():268] looking for notebook: 00-main.ipynb
2021-05-18 20:25:22,602 INFO    MainThread:628774 [wandb_init.py:_pause_backend():253] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7fc5473101d0>
2021-05-18 20:25:22,853 INFO    MainThread:628774 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-18 20:25:22,874 INFO    MainThread:628774 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-18 20:25:22,874 INFO    MainThread:628774 [jupyter.py:save_ipynb():268] looking for notebook: 00-main.ipynb
2021-05-18 20:25:23,360 INFO    MainThread:628774 [wandb_init.py:_pause_backend():253] saved code: <wandb.sdk.wandb_artifacts.Artifact object at 0x7fc5471763c8>
2021-05-18 20:25:23,365 INFO    MainThread:628774 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-18 20:25:23,372 INFO    MainThread:628774 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 20:25:23,372 INFO    MainThread:628774 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 20:25:23,372 INFO    MainThread:628774 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Weather-Clf/wandb/run-20210518_202523-uwmgmmto/logs/debug.log
2021-05-18 20:25:23,372 INFO    MainThread:628774 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Weather-Clf/wandb/run-20210518_202523-uwmgmmto/logs/debug-internal.log
2021-05-18 20:25:23,372 INFO    MainThread:628774 [wandb_init.py:init():369] calling init triggers
2021-05-18 20:25:23,372 INFO    MainThread:628774 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 20:25:23,372 INFO    MainThread:628774 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 2cnvf4vl
2021-05-18 20:25:23,373 INFO    MainThread:628774 [wandb_run.py:finish():1208] finishing run ranuga-d/Weather-Clf/2cnvf4vl
