2021-05-18 20:24:08,694 INFO    MainThread:628774 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 20:24:08,694 INFO    MainThread:628774 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 20:24:08,694 INFO    MainThread:628774 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Weather-Clf/wandb/run-20210518_202408-34mmwvxt/logs/debug.log
2021-05-18 20:24:08,694 INFO    MainThread:628774 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Weather-Clf/wandb/run-20210518_202408-34mmwvxt/logs/debug-internal.log
2021-05-18 20:24:08,695 INFO    MainThread:628774 [wandb_init.py:init():369] calling init triggers
2021-05-18 20:24:08,695 INFO    MainThread:628774 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 20:24:08,695 INFO    MainThread:628774 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 25u063kz
2021-05-18 20:24:08,696 INFO    MainThread:628774 [wandb_run.py:finish():1208] finishing run ranuga-d/Weather-Clf/25u063kz
2021-05-18 20:24:08,699 INFO    MainThread:628774 [jupyter.py:save_history():349] saving 30 cells to _session_history.ipynb
2021-05-18 20:24:08,705 INFO    MainThread:628774 [wandb_run.py:_config_callback():787] config_cb ('_wandb', 'session_history') code/_session_history.ipynb None
2021-05-18 20:24:08,721 INFO    MainThread:628774 [jupyter.py:save_ipynb():268] looking for notebook: 00-main.ipynb
2021-05-18 20:24:10,986 INFO    MainThread:628774 [wandb_init.py:_jupyter_teardown():267] saved code and history
2021-05-18 20:24:10,986 INFO    MainThread:628774 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-18 20:24:10,986 INFO    MainThread:628774 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-18 20:24:10,986 INFO    MainThread:628774 [wandb_run.py:_restore():1507] restore
2021-05-18 20:24:15,988 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: None
2021-05-18 20:24:18,396 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
  artifact_count: 3
}
pusher_stats {
  uploaded_bytes: 34732
  total_bytes: 34732
  deduped_bytes: 13081
}

2021-05-18 20:24:18,997 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
  artifact_count: 3
}
pusher_stats {
  uploaded_bytes: 34732
  total_bytes: 34732
  deduped_bytes: 13081
}

2021-05-18 20:24:19,516 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
}
pusher_stats {
  uploaded_bytes: 34732
  total_bytes: 51601
  deduped_bytes: 13081
}

2021-05-18 20:24:20,673 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 51254
  total_bytes: 64648
  deduped_bytes: 13081
}

2021-05-18 20:24:20,775 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 51254
  total_bytes: 64648
  deduped_bytes: 13081
}

2021-05-18 20:24:20,877 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 64648
  total_bytes: 64648
  deduped_bytes: 13081
}

2021-05-18 20:24:20,979 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 64648
  total_bytes: 64648
  deduped_bytes: 13081
}

2021-05-18 20:24:21,081 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 64648
  total_bytes: 64648
  deduped_bytes: 13081
}

2021-05-18 20:24:21,182 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 64648
  total_bytes: 64648
  deduped_bytes: 13081
}

2021-05-18 20:24:21,283 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 64648
  total_bytes: 64648
  deduped_bytes: 13081
}

2021-05-18 20:24:21,385 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 64648
  total_bytes: 64648
  deduped_bytes: 13081
}

2021-05-18 20:24:21,486 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 64648
  total_bytes: 64648
  deduped_bytes: 13081
}

2021-05-18 20:24:21,588 INFO    MainThread:628774 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  artifact_count: 3
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 64648
  total_bytes: 64648
  deduped_bytes: 13081
}

2021-05-18 20:24:22,881 INFO    MainThread:628774 [wandb_run.py:_show_files():1879] logging synced files
2021-05-18 20:24:22,885 INFO    MainThread:628774 [wandb_init.py:init():418] starting backend
2021-05-18 20:24:22,885 INFO    MainThread:628774 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-18 20:24:22,889 INFO    MainThread:628774 [backend.py:ensure_launched():132] starting backend process...
2021-05-18 20:24:22,924 INFO    MainThread:628774 [backend.py:ensure_launched():137] started backend process with pid: 637064
2021-05-18 20:24:22,925 INFO    MainThread:628774 [wandb_init.py:init():423] backend started and connected
2021-05-18 20:24:22,939 INFO    MainThread:628774 [wandb_init.py:init():465] updated telemetry
2021-05-18 20:24:22,940 INFO    MainThread:628774 [wandb_init.py:init():484] communicating current version
2021-05-18 20:24:23,791 INFO    MainThread:628774 [wandb_init.py:init():489] got version response 
2021-05-18 20:24:23,791 INFO    MainThread:628774 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-18 20:24:24,281 INFO    MainThread:628774 [wandb_init.py:init():522] starting run threads in backend
2021-05-18 20:24:29,296 INFO    MainThread:628774 [wandb_run.py:_console_start():1565] atexit reg
2021-05-18 20:24:29,296 INFO    MainThread:628774 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-18 20:24:29,296 INFO    MainThread:628774 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-18 20:24:29,296 INFO    MainThread:628774 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-18 20:24:29,296 INFO    MainThread:628774 [wandb_init.py:init():546] run started, returning control to user process
2021-05-18 20:24:44,595 INFO    MainThread:628774 [wandb_setup.py:_flush():69] setting env: {}
2021-05-18 20:24:44,595 INFO    MainThread:628774 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-18 20:24:44,595 INFO    MainThread:628774 [wandb_init.py:_log_setup():336] Logging user logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Weather-Clf/wandb/run-20210518_202444-2cnvf4vl/logs/debug.log
2021-05-18 20:24:44,595 INFO    MainThread:628774 [wandb_init.py:_log_setup():337] Logging internal logs to /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/CNN/Weather-Clf/wandb/run-20210518_202444-2cnvf4vl/logs/debug-internal.log
2021-05-18 20:24:44,595 INFO    MainThread:628774 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc5473042e8>
2021-05-18 20:24:44,596 INFO    MainThread:628774 [wandb_init.py:init():369] calling init triggers
2021-05-18 20:24:44,596 INFO    MainThread:628774 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-18 20:24:44,596 INFO    MainThread:628774 [wandb_init.py:init():391] re-initializing run, found existing run on stack: 34mmwvxt
2021-05-18 20:24:44,597 INFO    MainThread:628774 [wandb_run.py:finish():1208] finishing run ranuga-d/Weather-Clf/34mmwvxt
